--- 
title: "Data Science in Action During an Pandemic, Spring 2020"
author: "Jun Yan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
# bibliography: [stco.bib, book.bib, packages.bib]
biblio-style: chicago
link-citations: yes
description: "This is a series of notes for the students of 
  a seminar course taught at School of Statistics, SXUFE."
---

# 03/06

1. Going over the syllabus
1. Project management
   + Grouping
   + Member contributions
1. Presentation management
   + Sign up sheet?
1. Project ideas
   + Number of deaths due to COVID-19
   + Times series of historical data
   + Application and extension of eSIR
1. On Git and GitHub
   + It's a great tool
   + Not hard to pick up as long as you keep using it
   + Not that easy either

# 03/13

1. Questions from Git exercises
1. Demo Git clone, reproducible work, and contributions
   + Zhang, Yan (Chinese file name; location of working directory)
   + Xiao, Shiying
   + Jiao, Jieying
1. Building the Bookdown book from source
1. Discussion of Song's work (possible projects)
1. Logistics
   + Form teams
   + Sharpen skills
   + Identifying research questions
   + Find data
   + Proposal is due by week 5
1. Webinar and conference

# 03/20

1. Git issues; pull request
1. Demo from Shiying Xiao
1. Points of the building from source
    + It's the learning process that is of importance
	+ Search the error message
1. Logistics
    + Form teams
	    - Team leader
		- Team name
	+ Sign up
	+ Topic presentation resources
	    - arXiv; bioRXiv, medRXiv
		- Statistics Forum
	+ Time (lecture, study, and research)
1. A case study: ABO blood type and COVID-19


# 03/27

1. Examples of topic presentations
    + Styles/Formats
	+ Code for reproducibility
	+ Topics (Tom Kennen; Yishu Xue; Yiming Zhang)
1. Data sources
1. Logistics
    + Teams and proposals
	+ Coaches

# 04/03

1. Reproducibility (use relative path; etc.)
1. Tidyness (spacing; indentation; generated files; folders)
1. Git style: commit often; informative message
1. RMarkdown style:
    + keep the code clean and human-eye friendly
    + Use presentation style for presentations
1. Writing: 
    + Credit where it is due
	+ Back you what you say with citations
	+ Clarify your contribution in position of the existing literature


# 04/10

1. Logistics:
    + Confirm with your team coach
	+ Communicate through "Issues" on GitHub or direct commits.
	+ Review/search the literature
1. Interim project report due on Friday 05/22.
1. Final presentation order
